title: Le Marentin
email: lescordesassociees@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Le Marentin est un festival d'art de rue dans la communauté de communes de
  Landivisiau.
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

lang: fr

# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - .git
  - .bundle
  - .svn

# imagemagick:
# enabled: true
# widths:
#   - 512
#   - 128
#   - 0
# input_directories:
#   - _img_convert
# input_formats:
#   - ".jpg"
#   - ".jpeg"
# output_formats:
#   jpg: "-quality 85% -define jpeg:dct-method=float -strip -interlace Plane"
# #    webp: "-quality 100%"
